[package]
name = "fat_splitty_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "2.1.7"
teloxide = "0.13.0"
tokio = { version = "1.42.0", features = ["rt-multi-thread","macros"]}
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
